### ISSUE TITLE
downloader.py is not working 

### ISSUE THREAD

**Issue by savolla** [crackmes/crackmes#3]
Hi! thanks for making this awesome repository! I was trying to download all the crackmes with this script 
but I fail everytime I run it. It gives me the following error. Is it outdated? or is this just a problem with my system?

"
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7feb32366eb8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /api/v0/version?stream-channels=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb32366eb8>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ipfsapi/http.py", line 156, in _do_request
    return requests.request(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /api/v0/version?stream-channels=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb32366eb8>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./downloader.py", line 66, in <module>
    main()
  File "./downloader.py", line 52, in main
    api = ipfsapi.connect(ipfs_host, ipfs_port)
  File "/usr/lib/python3.7/site-packages/ipfsapi/client.py", line 75, in connect
    assert_version(client.version()['Version'])
  File "/usr/lib/python3.7/site-packages/ipfsapi/client.py", line 1878, in version
    return self._client.request('/version', decoder='json', **kwargs)
  File "/usr/lib/python3.7/site-packages/ipfsapi/http.py", line 38, in wrapper
    return func(self, *args, **merged)
  File "/usr/lib/python3.7/site-packages/ipfsapi/http.py", line 245, in request
    files, headers, data)
  File "/usr/lib/python3.7/site-packages/ipfsapi/http.py", line 181, in _request
    files=files, headers=headers, data=data)
  File "/usr/lib/python3.7/site-packages/ipfsapi/http.py", line 158, in _do_request
    six.raise_from(exceptions.ConnectionError(error), error)
  File "<string>", line 2, in raise_from
ipfsapi.exceptions.ConnectionError: ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5001): Max retries exceeded with url: /api/v0/version?stream-channels=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feb32366eb8>: Failed to establish a new connection: [Errno 111] Connection refused'))
"

**Comment by stkw0** [comment]
Are you running `ipfs daemon`?

**Comment by savolla** [comment]
I just installed go-ipfs package and did the following:
>> ipfs init
>> ipfs daemon
then I run the "downloader.py" script and there is just one empty directory called "19_you_cant_solve_this_yourself" 
and the output of the script is now:
"port 5001 host 127.0.0.1"

I think the script stucked there

**Comment by stkw0** [comment]
Yeah, it's trying to find peers. Currently this project is not developed, partially because nowadays there are more mature alternatives (like crackmes.one), and partially because we don't have too much time nor interest.

**Comment by savolla** [comment]
can you send me those crackmes please? I couldn't download those files.. I always searching peers as you said

**Comment by stkw0** [comment]
Yep, do you have an email or something?

**Comment by todduk** [comment]
Can you at least update the README to say this project doesn't work at the moment, thanks.

**Comment by Ooggle** [comment]
If there is still anyone here, it is possible to get the crackme too ?
Look forward to it thx.

**Comment by stkw0** [comment]
I have a backup. But if I remember correctly https://crackmes.one/ already have all these crackmes too.

**Comment by Ooggle** [comment]
Oh sorry for the delay regarding your message, thanks for the clarification, i will check out !
